version: "3"

services:
  # java-training用データベース
  learning-java-db:
    image: mysql:8.0.26
    container_name: learning_java_mysql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 127.0.0.1:3306:3306
      - 127.0.0.1:33060:33060
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=learn55
      - MYSQL_USER=training
      - MYSQL_PASSWORD=passwd
      - MYSQL_DATABASE=training
      - TZ=Asia/Tokyo
    volumes:
      - ./learning-java-db/initdb.d:/docker-entrypoint-initdb.d
      - vol-learning-java-db:/var/lib/mysql
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_bin
        --innodb_file_per_table
        --skip-character-set-client-handshake
        --lower_case_table_names=1
        --explicit_defaults_for_timestamp=1
        --sql_mode=ONLY_FULL_GROUP_BY,TRADITIONAL,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE
        --autocommit=0

volumes:
  vol-learning-java-db:
